homework9
reshet11/ios-homework pull request #9
Opened 2022-07-08 14:54 UTC by reshet11

2022-07-11 12:05 UTC, levkachev requested changes

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +    let arraySort = array.sorted()
тут достаточно написать просто print(array.sorted())

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +    switch arrayInsert.count {
👍

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +        print("\(text)")
тебе только исходя из задания не поэлементно надо распечатывать, а весь массив сразу целиком

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +func thirdFunc(arrayOne: [String], arrayTwo: [String]) {
не называй только функции "первая, вторая, десятая.."
называй по смыслу:
`calculateSumOfArrays(first: [String], second: [String])`

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +var teacherJournal = [String]()
ты здесь себе сам усложнил задачу, 
используй кортеж в качестве элемента массива и тебе тогда ниже не придется писать чехарду типа if i % 3 == 0 {

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +var teacherJournal = [String]()
но это решение оставь, с кортежами сделай отдельно

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +    print("name - \(arrayName[0]), surname - \(arrayName[1])")
напиши тело функции в 1 строчку

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +    print("nil")
логичнее в такой ситуации печатать "print("по ключу name значения в словаре не найдено")"

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +}
а ваще это все можно записать в одну строку "print(studentDict["name"])"

2022-07-11 12:05 UTC, levkachev commented on homework9.playground/Contents.swift
> +
созвонимся - расскажу как сделать красивее

2022-07-12 14:47 UTC, reshet11 commented on homework9.playground/Contents.swift
> +var teacherJournal = [String]()
сделал с кортежами отдельно

2022-08-21 18:05 UTC, merged